title:       Felix' tech blog
email:
author:      Felix Frank
description: "A blog about open source development, with bits about life, the universe, and everything. But mostly open source."
baseurl:     ""
url:         "http://ffrank.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: ffrank
stackoverflow_id: 3356612
twitter_username: felis_rex
google_plus_id: 111433443728862497850
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
gems:
  - jekyll-paginate
paginate:     3
sass:
  compressed: true
